services:
   jupyter:
      image: nben/drawfava:latest
      ports:
         - "127.0.0.1:${DRAWFAVA_PORT:-8181}:${DRAWFAVA_PORT:-8181}"
      environment:
        NB_UID: "${UID}"
        CHOWN_HOME: "yes"
        JUPYTER_TOKEN: ""
        JUPYTER_PORT: "${DRAWFAVA_PORT:-8181}"
        DOCKER_STACKS_JUPYTER_CMD: "notebook"
      volumes:
         - ${PWD}/annotations:/save:rw
         - ${PWD}/cache:/cache:rw
         - ${PWD}/.git:/git:r
      command: --NotebookApp.token='' --NotebookApp.password=''
